name: AntiRelog
main: com.github.r0306.antirelog.antirelog
version: 1.7.0
commands:
  ar:
    description: Shows plugin information.
    usage: /<command>
    aliases: [a, arl]
  antirelog:
    description: Shows plugin information.
    usage: /<command>
  ar t:
    description: Shows plugin information.
    usage: /<command>
  antirelog t:
    description: Displays combat time left.
    usage: /<command>
  ar time:
    description: Displays combat time left.
    usage: /<command>
  antirelog time:
    description: Displays combat time left.
    usage: /<command>
  ar unban:
    description: Unbans the selected player when they combat log.
    usage: /<command>
  antirelog unban:
    description: Unbans the selected player when they combat log.
    usage: /<command>
permissions:
    antirelog.*:
        description: Gives access to all PVP bypasses and AntiRelog commands.
        children:
            antirelog.pvpbypass: true
    antirelog.pvpbypass:
        description: Players who have this node can bypass all PVP battles and penalties.
        default: op
    antirelog.unban:
        description: Grants the ability to unban players who were originally banned through pvp logging.
        default: op
